- project:
    queue: blazar
    templates:
      - tempest-plugin-jobs
      - check-requirements
      - publish-openstack-docs-pti
    check:
      jobs:
        - blazar-tempest-plugin-base
        - blazar-tempest-plugin-ipv6-only
        - blazar-tempest-plugin-2024-2
        - blazar-tempest-plugin-2024-1
        - blazar-tempest-plugin-2023-2
        - blazar-tempest-plugin-2023-1
    gate:
      jobs:
        - blazar-tempest-plugin-base

- job:
    name: blazar-tempest-plugin-base
    description: |
      This is a base devstack job for Blazar.
      Former names for this job were:
        * blazar-devstack-dsvm
    parent: devstack-tempest
    required-projects: &blazar_required_projects
      - opendev.org/openstack/blazar
      - opendev.org/openstack/blazar-nova
      - opendev.org/openstack/python-blazarclient
      - opendev.org/openstack/blazar-tempest-plugin
    host-vars:
      controller:
        devstack_plugins:
          blazar: https://opendev.org/openstack/blazar
    vars: &blazar_base_vars
      tempest_test_regex: '^blazar_tempest_plugin'
      tox_envlist: all
      devstack_services:
        blazar: true
        blazar-a: true
        blazar-m: true
      tempest_plugins:
        - blazar-tempest-plugin
      tempest_concurrency: 1
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$

- job:
    name: blazar-tempest-plugin-ipv6-only
    description: |
      This is a base IPv6 devstack job for Blazar
      Former names for this job were:
        * blazar-devstack-dsvm-ipv6-only
    parent: devstack-tempest-ipv6
    required-projects: *blazar_required_projects
    host-vars:
      controller:
        devstack_plugins:
          blazar: https://opendev.org/openstack/blazar
    vars: *blazar_base_vars
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$

- job:
    name: blazar-tempest-plugin-2024-2
    parent: blazar-tempest-plugin-base
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2024.2

- job:
    name: blazar-tempest-plugin-2024-1
    parent: blazar-tempest-plugin-base
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2024.1
    vars:
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            resource_reservation:
              flavor_instance_plugin: false

- job:
    name: blazar-tempest-plugin-2023-2
    parent: blazar-tempest-plugin-base
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2023.2
    vars:
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            resource_reservation:
              flavor_instance_plugin: false

- job:
    name: blazar-tempest-plugin-2023-1
    parent: blazar-tempest-plugin-base
    nodeset: openstack-single-node-jammy
    override-checkout: stable/2023.1
    vars:
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            resource_reservation:
              flavor_instance_plugin: false
